# Generated by Django 5.2.5 on 2025-08-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['role', 'id']},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('general_manager', 'General Manager'), ('inventory_manager', 'Inventory Manager'), ('sales_manager', 'Sales Manager'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
