# Generated by Django 5.2.5 on 2025-09-02 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='sales_order',
            new_name='order_details',
        ),
    ]
