# Generated by Django 5.2.5 on 2025-09-03 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_rename_sales_order_invoice_order_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('paid', 'Paid')], default='pending', max_length=10),
        ),
    ]
