# Generated by Django 5.2.5 on 2025-08-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='sub_total',
        ),
    ]
