# Generated by Django 5.2.5 on 2025-09-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchaseorder_total_purchaseorderitem_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='quantity_ordered',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
