# Generated by Django 5.2.5 on 2025-09-03 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_alter_purchaseorderitem_quantity_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='total',
        ),
    ]
