# Generated by Django 5.2.5 on 2025-08-30 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_options_item_stock_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-updated_on', 'category']},
        ),
    ]
