# Generated by Django 5.2.5 on 2025-09-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
