# Generated by Django 5.2.5 on 2025-09-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='profit_margin_percent',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=20),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
